# Generated by Django 4.1 on 2022-08-12 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdressPlanes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("adress_UA", models.CharField(max_length=400)),
                ("adress_RU", models.CharField(max_length=400)),
                ("adress_EN", models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name="Allagancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Agancy", models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="CityPlanes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city_standart_UA", models.CharField(max_length=30, unique=True)),
                ("city_standart_RU", models.CharField(max_length=30, unique=True)),
                ("city_standart_EN", models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client", models.CharField(max_length=50, unique=True)),
                (
                    "agancy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="OhhRazomApi.allagancy",
                    ),
                ),
                (
                    "founder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContractorPlanes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Contractor_UA", models.CharField(max_length=100)),
                ("Contractor_RU", models.CharField(max_length=100, unique=True)),
                ("Contractor_EN", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ExcelPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fileName", models.CharField(max_length=100)),
                ("file", models.FileField(upload_to="OhhRazom/Excel/Price")),
            ],
        ),
        migrations.CreateModel(
            name="FormatPlanes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("format", models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="LocationPlanes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Location_UA", models.CharField(max_length=100)),
                ("Location_RU", models.CharField(max_length=100)),
                ("Location_EN", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="MultiplePhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photoName", models.CharField(max_length=100)),
                ("photo", models.ImageField(upload_to="OhhRazom/image/photo")),
            ],
        ),
        migrations.CreateModel(
            name="MultipleShema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shemaName", models.CharField(max_length=100)),
                ("shema", models.ImageField(upload_to="OhhRazom/image/shema")),
            ],
        ),
        migrations.CreateModel(
            name="Rk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("RK", models.CharField(max_length=100)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="OhhRazomApi.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SidePlanes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("side", models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="TypePlanes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("typeRU", models.CharField(max_length=40, unique=True)),
                ("typeEN", models.CharField(max_length=40, unique=True)),
                ("typeUA", models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Totalplanes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lat", models.CharField(max_length=100)),
                ("lng", models.CharField(max_length=100)),
                ("doors", models.CharField(max_length=40)),
                ("Self_number", models.CharField(max_length=40)),
                ("Razom_number", models.IntegerField(unique=True)),
                ("OTS", models.CharField(max_length=20)),
                ("GRP", models.CharField(max_length=20)),
                ("house", models.CharField(max_length=20)),
                ("route", models.IntegerField()),
                (
                    "imagePhoto",
                    models.ImageField(
                        default="OhhRazom/image/photo/1.jpg",
                        upload_to="OhhRazom/image/photo",
                    ),
                ),
                (
                    "imageShema",
                    models.ImageField(
                        default="OhhRazom/image/shema/1.jpg",
                        upload_to="OhhRazom/image/shema",
                    ),
                ),
                (
                    "Contractor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="OhhRazomApi.contractorplanes",
                    ),
                ),
                (
                    "adress",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="OhhRazomApi.adressplanes",
                    ),
                ),
                (
                    "city_standart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="OhhRazomApi.cityplanes",
                    ),
                ),
                (
                    "format",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="OhhRazomApi.formatplanes",
                    ),
                ),
                (
                    "loc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="OhhRazomApi.locationplanes",
                    ),
                ),
                (
                    "side",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="OhhRazomApi.sideplanes",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="OhhRazomApi.typeplanes",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("story", models.CharField(max_length=100)),
                ("color", models.CharField(default="#191970", max_length=15)),
                (
                    "rk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="OhhRazomApi.rk"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RkCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Grade", models.IntegerField(null=True)),
                ("comment", models.CharField(max_length=400, null=True)),
                ("price", models.IntegerField(null=True)),
                (
                    "Razom_number",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="OhhRazomApi.totalplanes",
                    ),
                ),
                (
                    "rk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="OhhRazomApi.rk"
                    ),
                ),
                (
                    "story",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="OhhRazomApi.story",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReachCity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reach", models.CharField(max_length=40)),
                ("frequency", models.CharField(default="0", max_length=20)),
                ("period", models.CharField(default="0", max_length=20)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="OhhRazomApi.cityplanes",
                    ),
                ),
                (
                    "rk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="OhhRazomApi.rk"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PermisionUsersClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="OhhRazomApi.client",
                    ),
                ),
                (
                    "userId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
