# Generated by Django 4.1 on 2022-08-29 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("OhhRazomApi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rkcompany",
            name="GradeNew",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="rkcompany",
            name="Razom_number",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rz",
                to="OhhRazomApi.totalplanes",
            ),
        ),
    ]
