# Generated by Django 4.1 on 2022-10-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OhhRazomApi", "0002_client_isactive"),
    ]

    operations = [
        migrations.AddField(
            model_name="rk",
            name="Stage",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="rk",
            name="create_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="rk", name="end_date", field=models.DateTimeField(auto_now=True),
        ),
    ]
